---
title: "shiny of amazon alexa"
author: "Rahmat Zumarli 123170011 || M. Ilham Robbani 123170021"
date: "5/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**`global`**
```{r global}
library(dplyr)
library(vroom)
library(here)
library(tidyverse)
library(ggplot2)
library(plotly)
library(tidytext)
library(wordcloud)
library(wordcloud2)
library(reshape2)
library(shiny)
library(tm)
library(memoise)

womanclothing = vroom(here("womensclothing.csv"))
option_classname = unique(womanclothing$`Class Name`)

count_reviews = function() {
  womanclothing %>%
    nrow()
}

count_sentiments = function(x) {
  womanclothing %>%
      unnest_tokens(word, `Review Text`) %>%
      anti_join(stop_words) %>%
      inner_join(get_sentiments("bing")) %>%
      count(sentiment) %>%
      filter(sentiment == x)
}

table_womanclothing = function() {
  womanclothing %>%
      mutate(`Positive Feedback Count` = case_when(
        `Positive Feedback Count` == 1 ~ "Positive",
        TRUE ~ "Negative"
      )) %>%
      select(Age,Title,`Review Text`,`Positive Feedback Count`,`Class Name`) %>%
      head(50)
}
```

**`ui`**
```{r ui}
ui = fluidPage(
  title = "Sentiment Analysis of Woman Clothing E-Commerce Review",
  headerPanel("Sentiment Analysis of Woman Clothing E-Commerce Review"),
  
  fluidRow(
    column(
      4,
      h3("Total Reviews"),
      h4(strong(textOutput(outputId = "total_reviews")))
    ),
    column(
      4,
      h3("Positive Words"),
      h4(strong(textOutput(outputId = "total_positive")))
    ),
    column(
      4,
      h3("Negative Words"),
      h4(strong(textOutput(outputId = "total_negative")))
    )
  ),

  sidebarLayout(
    sidebarPanel(
      selectInput(
        inputId = "Class Name",
        label = "Variation of Woman Clothing",
        choices = option_classname,
        multiple = TRUE,
        selected = option_classname[[1]]
      )
    ),
    mainPanel(
      plotlyOutput(outputId = "plot_word_freq", height = "700px"),
      br(),
      plotlyOutput(outputId = "plot_word_usage", height = "700px"),
      h3("Words Cloud", align = "center"),
      plotOutput(outputId = "plot_word_cloud", height = "1200px"),
      h3("Table Reviews"),
      tableOutput(outputId = "plot_reviews")
    )
  )
)
```

**`server`**
```{r server}
server = function(input, output, session) {
  plot_word_freq = reactive({
    womanclothing %>% 
      group_by(`Class Name`) %>%
      unnest_tokens(word, `Review Text`) %>%
      group_by(`Class Name`) %>%
      anti_join(stop_words) %>%
      count(word, sort = T) %>%
      na.omit() %>%
      filter(n >= 1000) %>%
      ggplot(aes(x = reorder(word, n), y = n, fill = `Class Name`)) +
        geom_bar(stat = "identity") +
        coord_flip() +
        labs(
          x = "Words",
          y = "Frequency",
          title = "Word Frequency Graphic"
        ) +
        theme_light()
  })
  
  output$plot_word_freq = renderPlotly({
    ggplotly(plot_word_freq())
  })
  
  plot_word_usage = reactive({
    womanclothing %>%
      filter(`Class Name` %in% input$`Class Name`) %>%
      unnest_tokens(word, `Review Text`) %>%
      anti_join(stop_words) %>%
      inner_join(get_sentiments("bing")) %>%
      group_by(sentiment, `Class Name`) %>%
      count(word) %>%
      top_n(10) %>%
      ggplot(aes(x = reorder(word, n), y = n, fill = `Class Name`)) +
        geom_col(show.legend = T) +
        coord_flip() +
        facet_wrap(~sentiment, scales = "free_y") +
        labs(
          x = "Words",
          y = "Frequency",
          title = "Word Usage Graphic"
        ) +
        theme_light()
  })
  
  output$plot_word_usage = renderPlotly({
    ggplotly(plot_word_usage())
  })

  output$plot_word_cloud = renderPlot({
    womanclothing %>%
      filter(`Class Name` %in% input$`Class Name`) %>%
      unnest_tokens(word, `Review Text`) %>%
      anti_join(stop_words) %>%
      inner_join(get_sentiments("bing")) %>%
      count(word, sentiment) %>% 
      acast(word~sentiment, value.var = "n", fill = 0) %>% 
      comparison.cloud(colors = c("#1b2a49", "#00909e"), max.words = 200, scale = c(4,1))
  })
  
  output$total_reviews = renderText({
    count_reviews()
  })
  
  output$total_positive = renderText({
    count_sentiments("positive")$n
  })
  
  output$total_negative = renderText({
    count_sentiments("negative")$n
  })
  
  output$plot_reviews = renderTable({
    table_womanclothing()
  })
}
```

**`run-app`**
```{r run-app}
shinyApp(ui = ui, server = server)
```

